### ISSUE TITLE
collides with universal graves 

### ISSUE THREAD

**Issue by Seegras** [AmyMialeeMods/piercingpaxels#21]
Crashes on start on 1.20 if universal graves https://modrinth.com/mod/universal-graves/version/3.0.0-beta.2+1.20 is installed. 

No idea where the problem lies. 

```
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_1277.<init>(class_1277.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.<clinit>(class_2248.java:242) ~[client-intermediary.jar:?]
	at eu.pb4.polymer.core.impl.PolymerImplUtils.<clinit>(PolymerImplUtils.java:46) ~[polymer-core-0.5.0+1.20-2ec132c13bcc3f2d.jar:?]
	at net.minecraft.class_2370.handler$cni000$polymer-core$polymer$storeStatus(class_2370.java:3050) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7922.method_39673()" because "net.minecraft.class_7923.field_41178" is null
	at net.minecraft.class_1799.method_28376(class_1799.java:81) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_1799.<clinit>(class_1799.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_1277.<init>(class_1277.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.<clinit>(class_2248.java:242) ~[client-intermediary.jar:?]
	at eu.pb4.polymer.core.impl.PolymerImplUtils.<clinit>(PolymerImplUtils.java:46) ~[polymer-core-0.5.0+1.20-2ec132c13bcc3f2d.jar:?]
	at net.minecraft.class_2370.handler$cni000$polymer-core$polymer$storeStatus(class_2370.java:3050) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 5 more

```

**Comment by Patbox** [comment]
I'm looking at this error and what the fuck

**Comment by AmyMialee** [comment]
That is really odd.

**Comment by Patbox** [comment]
After looking at it more, it's an issue caused by Registry class (via ROOT registry) loading PolymerImplUtils to invoke an event for initial registration, which loads Block class, which loads SimpleInventory class (because of [this mixin](https://github.com/AmyMialeeMods/piercingpaxels/blob/main/common/src/main/java/xyz/amymialee/piercingpaxels/mixin/BlockMixin.java)), which loads ItemStack class, which tries to create codec depending on Registries.ITEM, which at this stage is still `null` (Registries didn't load fully yet). Fun issue, isn't it.

**Comment by Patbox** [comment]
Install latest version of https://modrinth.com/mod/polymer/versions, should solve the issue

**Comment by nirurin** [comment]
> Install latest version of https://modrinth.com/mod/polymer/versions, should solve the issue

I have this same issue (or at least very similar) but installing polymer on the client does nothing. Still exit code 1. Thought it's possible my 'exit code 1' is being caused by some other bug.
